---
layout: page
title: Analysis of Fatty Recipes and User Ratings
description: An exploration into the relationship between perceived rating of food and total fat content, among other nutritional components.
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
---
