---
layout: page
title: Food and Time/Money Cost
description: An exploration into the relationship between perceived rating of food and time/money costs.
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
---
